/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";
import type { Checked, Check } from "./types";
import type {
  ClassificationLabelFeildValue,
  ClassificationLabelValue,
  CreateDraftAction,
  Draft,
  Message,
  MessagePart,
  MessagePartBody,
  MessagePartHeader,
  Resume,
} from "./types";
import type * as types from "./types";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
  value: T;
  state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
  export interface ClassificationLabelFeildValue {
    fieldId?: string | null;
    selection?: string | null;
  }
  export interface ClassificationLabelValue {
    labelId?: string | null;
    fields: ClassificationLabelFeildValue[];
  }
  export interface CreateDraftAction {}
  export interface Draft {
    id?: string | null;
    message?: Message | null;
  }
  export interface Message {
    id?: string | null;
    threadId?: string | null;
    labelIds: string[];
    snippet?: string | null;
    historyId?: string | null;
    internalDate?: string | null;
    payload?: MessagePart | null;
    sizeEstimate?: number | null;
    raw?: string | null;
    classificationLabelValues?: ClassificationLabelValue | null;
  }
  export interface MessagePart {
    partId?: string | null;
    mimeType?: string | null;
    filename?: string | null;
    headers: MessagePartHeader[];
    body?: MessagePartBody | null;
    parts: MessagePart[];
  }
  export interface MessagePartBody {
    size?: number | null;
    data?: string | null;
    attachmentId?: string | null;
  }
  export interface MessagePartHeader {
    name?: string | null;
    value?: string | null;
  }
  export interface Resume {
    name?: string | null;
    email?: string | null;
    experience: string[];
    skills: string[];
  }
}
