/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml";
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
  ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
  : T | null;

export interface Checked<T, CheckName extends string = string> {
  value: T;
  checks: Record<CheckName, Check>;
}

export interface Check {
  name: string;
  expr: string;
  status: "succeeded" | "failed";
}

export function all_succeeded<CheckName extends string>(
  checks: Record<CheckName, Check>,
): boolean {
  return get_checks(checks).every((check) => check.status === "succeeded");
}

export function get_checks<CheckName extends string>(
  checks: Record<CheckName, Check>,
): Check[] {
  return Object.values(checks);
}
export interface ClassificationLabelFeildValue {
  fieldId: string;
  selection: string;
}

export interface ClassificationLabelValue {
  labelId: string;
  fields: ClassificationLabelFeildValue[];
}

export interface CreateDraftAction {}

export interface Draft {
  id: string;
  message: Message;
}

export interface Message {
  id: string;
  threadId: string;
  labelIds: string[];
  snippet: string;
  historyId: string;
  internalDate: string;
  payload: MessagePart;
  sizeEstimate: number;
  raw: string;
  classificationLabelValues: ClassificationLabelValue;
}

export interface MessagePart {
  partId: string;
  mimeType: string;
  filename: string;
  headers: MessagePartHeader[];
  body: MessagePartBody;
  parts: MessagePart[];
}

export interface MessagePartBody {
  size: number;
  data: string;
  attachmentId: string;
}

export interface MessagePartHeader {
  name: string;
  value: string;
}

export interface Resume {
  name: string;
  email: string;
  experience: string[];
  skills: string[];
}
