/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    CalendarAction: ClassViewer<'CalendarAction', "action" | "summary" | "payload">;
    
    CalendarPayload: ClassViewer<'CalendarPayload', "title" | "start" | "end" | "description" | "location">;
    
    ClassificationLabelFeildValue: ClassViewer<'ClassificationLabelFeildValue', "fieldId" | "selection">;
    
    ClassificationLabelValue: ClassViewer<'ClassificationLabelValue', "labelId" | "fields">;
    
    CreateDocAction: ClassViewer<'CreateDocAction', "title" | "content" | "topics" | "learned_profile">;
    
    CreateDraftAction: ClassViewer<'CreateDraftAction'>;
    
    Draft: ClassViewer<'Draft', "id" | "message">;
    
    LearnedProfile: ClassViewer<'LearnedProfile', "learning_style" | "preferred_formats">;
    
    Message: ClassViewer<'Message', "id" | "threadId" | "labelIds" | "snippet" | "historyId" | "internalDate" | "payload" | "sizeEstimate" | "raw" | "classificationLabelValues">;
    
    MessagePart: ClassViewer<'MessagePart', "partId" | "mimeType" | "filename" | "headers" | "body" | "parts">;
    
    MessagePartBody: ClassViewer<'MessagePartBody', "size" | "data" | "attachmentId">;
    
    MessagePartHeader: ClassViewer<'MessagePartHeader', "name" | "value">;
    
    ParsedIntent: ClassViewer<'ParsedIntent', "intent" | "summary">;
    
    Resume: ClassViewer<'Resume', "name" | "email" | "experience" | "skills">;
    
    
    IntentType: EnumViewer<'IntentType', "Calendar" | "Doc" | "Mail" | "Unknown">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "CalendarAction","CalendarPayload","ClassificationLabelFeildValue","ClassificationLabelValue","CreateDocAction","CreateDraftAction","Draft","LearnedProfile","Message","MessagePart","MessagePartBody","MessagePartHeader","ParsedIntent","Resume",
          ]),
          enums: new Set([
            "IntentType",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.CalendarAction = this.tb.classViewer("CalendarAction", [
          "action","summary","payload",
        ]);
        
        this.CalendarPayload = this.tb.classViewer("CalendarPayload", [
          "title","start","end","description","location",
        ]);
        
        this.ClassificationLabelFeildValue = this.tb.classViewer("ClassificationLabelFeildValue", [
          "fieldId","selection",
        ]);
        
        this.ClassificationLabelValue = this.tb.classViewer("ClassificationLabelValue", [
          "labelId","fields",
        ]);
        
        this.CreateDocAction = this.tb.classViewer("CreateDocAction", [
          "title","content","topics","learned_profile",
        ]);
        
        this.CreateDraftAction = this.tb.classViewer("CreateDraftAction", [
          
        ]);
        
        this.Draft = this.tb.classViewer("Draft", [
          "id","message",
        ]);
        
        this.LearnedProfile = this.tb.classViewer("LearnedProfile", [
          "learning_style","preferred_formats",
        ]);
        
        this.Message = this.tb.classViewer("Message", [
          "id","threadId","labelIds","snippet","historyId","internalDate","payload","sizeEstimate","raw","classificationLabelValues",
        ]);
        
        this.MessagePart = this.tb.classViewer("MessagePart", [
          "partId","mimeType","filename","headers","body","parts",
        ]);
        
        this.MessagePartBody = this.tb.classViewer("MessagePartBody", [
          "size","data","attachmentId",
        ]);
        
        this.MessagePartHeader = this.tb.classViewer("MessagePartHeader", [
          "name","value",
        ]);
        
        this.ParsedIntent = this.tb.classViewer("ParsedIntent", [
          "intent","summary",
        ]);
        
        this.Resume = this.tb.classViewer("Resume", [
          "name","email","experience","skills",
        ]);
        
        
        this.IntentType = this.tb.enumViewer("IntentType", [
          "Calendar","Doc","Mail","Unknown",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}